 local menue0e4fc6213e8b3593495a7260c3a4c2e = {
     {"Onboard", "onboard", "/usr/share/icons/hicolor/16x16/apps/onboard.png" },
 }

 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Archive Manager", "file-roller "},
     {"Atom", "env ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /usr/bin/atom ", "/usr/share/icons/hicolor/16x16/apps/atom.png" },
     {"Azure Data Studio", "/opt/azuredatastudio/bin/azuredatastudio --no-sandbox --unity-launch ", "/usr/share/icons/azuredatastudio.png" },
     {"BlueProximity", "start_proximity.sh", "/usr/share/pixmaps/blueproximity.xpm" },
     {"Calculator", "gnome-calculator"},
     {"Character Map", "gucharmap", "/usr/share/icons/gnome/16x16/apps/accessories-character-map.png" },
     {"ClamTk", "clamtk ", "/usr/share/pixmaps/clamtk.png" },
     {"Disks", "gnome-disks"},
     {"DockX", "dockx", "/usr/share/icons/hicolor/16x16/apps/dockbarx.png" },
     {"DockbarX Preference", "dbx_preference", "/usr/share/icons/hicolor/16x16/apps/dockbarx.png" },
     {"Document Viewer", "xreader ", "/usr/share/icons/hicolor/16x16/apps/xreader.png" },
     {"FSearch", "fsearch"},
     {"GVim", "gvim -f ", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
     {"HP Device Manager", "hp-toolbox", "///usr/share/hplip/data/images/128x128/hp_logo.png" },
     {"Image Optimizer", "com.github.gijsgoudzwaard.image-optimizer", "/usr/share/icons/hicolor/16x16/apps/com.github.gijsgoudzwaard.image-optimizer.svg" },
     {"Image Viewer", "gpicview ", "/usr/share/icons/hicolor/48x48/apps/gpicview.png" },
     {"Leafpad", "leafpad ", "/usr/share/icons/hicolor/16x16/apps/leafpad.png" },
     {"Maps", "gapplication launch org.gnome.Maps "},
     {"Onboard", "onboard", "/usr/share/icons/hicolor/16x16/apps/onboard.png" },
     {"PDF Tricks", "com.github.muriloventuroso.pdftricks", "/usr/share/icons/hicolor/128x128/apps/com.github.muriloventuroso.pdftricks.svg" },
     {"Passwords and Keys", "seahorse"},
     {"Piper", "piper"},
     {"QTalarm", "qtalarm", "/usr/share/icons/hicolor/16x16/apps/1349069370_Alarm_Clock.png" },
     {"Screenkey", "screenkey", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-keyboard-shortcuts.png" },
     {"Screenshot", "xfce4-screenshooter", "/usr/share/icons/hicolor/16x16/apps/org.xfce.screenshooter.png" },
     {"Shutter Encoder", "shutter-encoder", "///usr/lib/Shutter Encoder/usr/bin/icon.png" },
     {"Simplenote", "/opt/Simplenote/simplenote ", "/usr/share/icons/hicolor/16x16/apps/simplenote.png" },
     {"Solanum", "solanum"},
     {"Text Editor", "xed ", "/usr/share/icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"To Do", "gnome-todo"},
     {"USB Image Writer", "mintstick -m iso"},
     {"USB Stick Formatter", "mintstick -m format"},
     {"Vim", "xterm -e vim ", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
     {"Visual Studio Code", "/usr/bin/code --no-sandbox --unity-launch ", "/usr/share/icons/visual-studio-code.png" },
     {"Winetricks", "winetricks --gui"},
     {"nitrogen", "nitrogen", "/usr/share/icons/hicolor/16x16/apps/nitrogen.png" },
     {"picom", "picom"},
     {"xppentablet", "/usr/lib/pentablet/pentablet.sh", "///usr/share/icons/pentablet.png" },
 }

 local menu78059f1898ed518c6ccd6a6392fa82c1 = {
     {"AUR", "xdg-open https://aur.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Bugs", "xdg-open https://bugs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Developers", "xdg-open http://www.archlinux.org/developers/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Documentation", "xdg-open https://wiki.archlinux.org/index.php/Official_Arch_Linux_Install_Guide", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Donate", "xdg-open http://www.archlinux.org/donate/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Forum", "xdg-open https://bbs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Homepage", "xdg-open http://www.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"SVN", "xdg-open http://projects.archlinux.org/svntogit/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Schwag", "xdg-open http://www.zazzle.com/archlinux/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Wiki", "xdg-open https://wiki.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"Steam (Native)", "/usr/bin/steam-native ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Agave", "agave", "/usr/share/icons/hicolor/16x16/apps/agave.png" },
     {"Blender", "blender "},
     {"Boxy SVG", "env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/boxy-svg_boxy-svg.desktop /var/lib/snapd/snap/bin/boxy-svg ", "///var/lib/snapd/snap/boxy-svg/107/meta/gui/boxy-svg.svg" },
     {"Darktable", "/usr/bin/darktable ", "/usr/share/icons/hicolor/16x16/apps/darktable.png" },
     {"Document Scanner", "simple-scan"},
     {"Document Viewer", "evince "},
     {"GNU Image Manipulation Program", "gimp-2.10 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Image Optimizer", "com.github.gijsgoudzwaard.image-optimizer", "/usr/share/icons/hicolor/16x16/apps/com.github.gijsgoudzwaard.image-optimizer.svg" },
     {"Image Viewer", "gpicview ", "/usr/share/icons/hicolor/48x48/apps/gpicview.png" },
     {"Image Viewer", "eog "},
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/org.inkscape.Inkscape.png" },
     {"KolourPaint", "kolourpaint ", "/usr/share/icons/hicolor/16x16/apps/kolourpaint.png" },
     {"Krita", "krita ", "/usr/share/icons/hicolor/16x16/apps/krita.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Okular", "okular ", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Peek", "peek"},
     {"QtQR", "qtqr "},
     {"RawTherapee", "rawtherapee ", "/usr/share/icons/hicolor/16x16/apps/rawtherapee.png" },
     {"XDvi", "xdvi "},
     {"drawio", "/opt/drawio/drawio ", "/usr/share/icons/hicolor/16x16/apps/drawio.png" },
     {"gThumb", "gthumb ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.gThumb.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"AnyDesk", "/usr/bin/anydesk ", "/usr/share/pixmaps/anydesk.svg" },
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Brave", "brave ", "/usr/share/icons/hicolor/16x16/apps/brave-desktop.png" },
     {"DavMail", "davmail", "/usr/share/icons/hicolor/16x16/apps/davmail.png" },
     {"Discord", "/usr/bin/discord --force-device-scale-factor=1 --disable-gpu-driver-bug-workarounds --disable-gpu-vsync --use-gl=desktop --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy --disable-features=UseOzonePlatform,UseChromeOSDirectVideoDecoder --enable-features=VaapiVideoEncoder,VaapiVideoDecoder,WebUIDarkMode --force-dark-mode", "/usr/share/pixmaps/discord.png" },
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Google Chrome", "/usr/bin/google-chrome-stable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"Google Chrome (beta)", "/usr/bin/google-chrome-beta ", "/usr/share/icons/hicolor/16x16/apps/google-chrome-beta.png" },
     {"Insync", "insync start"},
     {"KDE Connect", "kdeconnect-app"},
     {"KDE Connect Indicator", "kdeconnect-indicator"},
     {"KDE Connect SMS", "kdeconnect-sms"},
     {"LanXchange", "lxcr", "/usr/share/pixmaps/lanxchange.png" },
     {"Microsoft Teams - Preview", "teams ", "/usr/share/pixmaps/teams.png" },
     {"Mullvad VPN", "\"/opt/Mullvad VPN/mullvad-vpn\" ", "/usr/share/icons/hicolor/16x16/apps/mullvad-vpn.png" },
     {"Open on connected device via KDE Connect", "kdeconnect-handler --open "},
     {"Prospect Mail", "\"/opt/Prospect Mail/prospect-mail\" --force-device-scale-factor=1 --disable-gpu-driver-bug-workarounds --disable-gpu-vsync --use-gl=desktop --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy --disable-features=UseOzonePlatform,UseChromeOSDirectVideoDecoder --enable-features=VaapiVideoEncoder,VaapiVideoDecoder,WebUIDarkMode --force-dark-mode "},
     {"Slack", "/usr/bin/slack -s ", "/usr/share/pixmaps/slack.png" },
     {"Steam (Native)", "/usr/bin/steam-native ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"TeamViewer", "/opt/teamviewer/tv_bin/script/teamviewer", "/usr/share/icons/hicolor/16x16/apps/TeamViewer.png" },
     {"Telegram Desktop", "telegram-desktop -- ", "/usr/share/icons/hicolor/16x16/apps/telegram.png" },
     {"Tor Browser (en-US)", "tor-browser ", "/usr/share/icons/hicolor/128x128/apps/tor-browser.png" },
     {"Torrential", "com.github.davidmhewitt.torrential ", "/usr/share/icons/hicolor/16x16/apps/com.github.davidmhewitt.torrential.svg" },
     {"Transmission", "transmission-gtk ", "/usr/share/pixmaps/transmission.png" },
     {"Trello", "trello --force-device-scale-factor=1 --disable-gpu-driver-bug-workarounds --use-gl=desktop --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy --enable-features=VaapiVideoDecoder --disable-features=UseOzonePlatform", "/usr/share/pixmaps/trello.png" },
     {"VMware Horizon Client", "vmware-view ", "/usr/share/icons/hicolor/16x16/apps/vmware-horizon.png" },
     {"Viber", "viber ", "/usr/share/icons/hicolor/16x16/apps/viber.png" },
     {"Video Downloader", "video-downloader", "/usr/share/icons/hicolor/16x16/apps/com.github.unrud.VideoDownloader.png" },
     {"What IP", "/usr/bin/whatip "},
     {"Zoom", "/usr/bin/zoom ", "/usr/share/pixmaps/Zoom.png" },
     {"qBittorrent", "qbittorrent ", "/usr/share/icons/hicolor/16x16/apps/qbittorrent.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Calendar", "gnome-calendar "},
     {"Document Viewer", "evince "},
     {"Evolution", "evolution "},
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Okular", "okular ", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Prospect Mail", "\"/opt/Prospect Mail/prospect-mail\" --force-device-scale-factor=1 --disable-gpu-driver-bug-workarounds --disable-gpu-vsync --use-gl=desktop --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy --disable-features=UseOzonePlatform,UseChromeOSDirectVideoDecoder --enable-features=VaapiVideoEncoder,VaapiVideoDecoder,WebUIDarkMode --force-dark-mode "},
     {"ReText", "/usr/bin/retext ", "/usr/share/icons/hicolor/16x16/apps/retext.png" },
     {"qpdfview", "qpdfview --unique "},
 }

 local menu6311ae17c1ee52b36e68aaf4ad066387 = {
     {"zamautosat", "ZamAutoSat"},
     {"zamaximx2", "ZaMaximX2"},
     {"zamcomp", "ZamComp"},
     {"zamcompx2", "ZamCompX2"},
     {"zamdelay", "ZamDelay"},
     {"zamdynamiceq", "ZamDynamicEQ"},
     {"zameq2", "ZamEQ2"},
     {"zamgate", "ZamGate"},
     {"zamgatex2", "ZamGateX2"},
     {"zamgeq31", "ZamGEQ31"},
     {"zamheadx2", "ZamHeadX2"},
     {"zammulticompx2", "com.zamaudio.zammulticompx2"},
     {"zamphono", "ZamPhono"},
     {"zamtube", "ZamTube"},
     {"zamulticomp", "ZaMultiComp"},
     {"zamverb", "ZamVerb"},
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Android Studio", "android-studio ", "/usr/share/pixmaps/android-studio.png" },
     {"Arduino IDE", "arduino ", "/usr/share/icons/hicolor/16x16/apps/arduino.png" },
     {"Atom", "env ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /usr/bin/atom ", "/usr/share/icons/hicolor/16x16/apps/atom.png" },
     {"Azure Data Studio", "/opt/azuredatastudio/bin/azuredatastudio --no-sandbox --unity-launch ", "/usr/share/icons/azuredatastudio.png" },
     {"Bluefish Editor", "bluefish ", "/usr/share/icons/hicolor/16x16/apps/bluefish.png" },
     {"Boxes", "gnome-boxes "},
     {"Brackets", "/opt/brackets/brackets "},
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Eclipse", "eclipse", "/usr/share/icons/hicolor/16x16/apps/eclipse.png" },
     {"Electron", "electron6 ", "/usr/share/pixmaps/electron6.png" },
     {"Electron", "electron ", "/usr/share/pixmaps/electron.png" },
     {"Electron 11", "electron11 ", "/usr/share/pixmaps/electron11.png" },
     {"Electron 12", "electron12 ", "/usr/share/pixmaps/electron12.png" },
     {"Electron 15", "electron15 ", "/usr/share/pixmaps/electron15.png" },
     {"Electron 16", "electron16 ", "/usr/share/pixmaps/electron16.png" },
     {"Electron 9", "electron9 ", "/usr/share/pixmaps/electron9.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/32x32/apps/fluid.png" },
     {"Geany", "geany ", "/usr/share/icons/hicolor/16x16/apps/geany.png" },
     {"Gendarme", "/usr/bin/gendarme-wizard", "/usr/share/pixmaps/gendarme.svg" },
     {"GitHub Desktop", "/usr/bin/github-desktop ", "/usr/share/icons/hicolor/32x32/apps/github-desktop.png" },
     {"Image Optimizer", "com.github.gijsgoudzwaard.image-optimizer", "/usr/share/icons/hicolor/16x16/apps/com.github.gijsgoudzwaard.image-optimizer.svg" },
     {"IntelliJ IDEA Community Edition", "/usr/bin/idea ", "/usr/share/pixmaps/idea.png" },
     {"IntelliJ IDEA Community Edition", "\"/usr/share/idea/bin/idea.sh\" ", "///usr/share/idea/bin/idea.svg" },
     {"Meld", "meld ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.meld.png" },
     {"Mono Documentation", "/usr/bin/monodoc", "/usr/share/icons/hicolor/16x16/apps/monodoc.png" },
     {"MonoDevelop", "monodevelop ", "/usr/share/icons/hicolor/16x16/apps/monodevelop.png" },
     {"MySQL Workbench", "mysql-workbench ", "/usr/share/icons/hicolor/16x16/apps/mysql-workbench.png" },
     {"OpenJDK 1.7.0 for x86_64 Monitoring & Management Console (1.7.0_261-b02)", "_SDKBINDIR_/jconsole"},
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"SASM", "sasm", "///usr/share/sasm/sasm.png" },
     {"Sublime Text", "subl ", "/usr/share/icons/hicolor/16x16/apps/sublime-text.png" },
     {"Visual Studio Code", "/usr/bin/code --no-sandbox --unity-launch ", "/usr/share/icons/visual-studio-code.png" },
     {"gsharp", "/usr/bin/gsharp"},
 }

 local menu80d754c83abbbd4ef5d150904efcc86c = {
     {"GNU PSPP", "psppire ", "/usr/share/icons/hicolor/16x16/apps/pspp.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"3BandEQ", "/usr/bin/3BandEQ"},
     {"3BandSplitter", "/usr/bin/3BandSplitter"},
     {"Aegisub", "env GDK_BACKEND=x11 aegisub-3.2 ", "/usr/share/icons/hicolor/16x16/apps/aegisub.png" },
     {"AmplitudeImposer", "/usr/bin/AmplitudeImposer"},
     {"Ardour", "ardour6", "/usr/share/icons/hicolor/16x16/apps/ardour6.png" },
     {"Audacity", "env UBUNTU_MENUPROXY=0 audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Avidemux", "avidemux3_qt5 ", "/usr/share/icons/hicolor/128x128/apps/org.avidemux.Avidemux.png" },
     {"Brasero", "brasero ", "/usr/share/icons/hicolor/16x16/apps/brasero.png" },
     {"Cheese", "cheese"},
     {"Clapper", "com.github.rafostar.Clapper "},
     {"CycleShifter", "/usr/bin/CycleShifter"},
     {"Echomixer", "echomixer", "/usr/share/icons/hicolor/48x48/apps/echomixer.png" },
     {"Envy24 Control", "envy24control", "/usr/share/icons/hicolor/48x48/apps/envy24control.png" },
     {"HDAJackRetask", "hdajackretask"},
     {"HDSPConf", "hdspconf", "/usr/share/icons/hicolor/48x48/apps/hdspconf.png" },
     {"HDSPMixer", "hdspmixer", "/usr/share/icons/hicolor/48x48/apps/hdspmixer.png" },
     {"HandBrake", "ghb "},
     {"Hwmixvolume", "hwmixvolume", "/usr/share/icons/hicolor/48x48/apps/hwmixvolume.png" },
     {"Kars", "/usr/bin/Kars"},
     {"LMMS", "lmms ", "/usr/share/icons/hicolor/16x16/apps/lmms.png" },
     {"LosslessCut", "losslesscut", "/usr/share/pixmaps/losslesscut.svg" },
     {"MVerb", "/usr/bin/MVerb"},
     {"MaBitCrush", "/usr/bin/MaBitCrush"},
     {"MaFreeverb", "/usr/bin/MaFreeverb"},
     {"MaGigaverb", "/usr/bin/MaGigaverb"},
     {"MaPitchshift", "/usr/bin/MaPitchshift"},
     {"MakeMKV", "makemkv", "/usr/share/icons/hicolor/16x16/apps/makemkv.png" },
     {"Nekobi", "/usr/bin/Nekobi"},
     {"New Session Manager (Legacy GUI)", "nsm-legacy-gui"},
     {"OBS Studio", "obs", "/usr/share/icons/hicolor/128x128/apps/com.obsproject.Studio.png" },
     {"Peek", "peek"},
     {"PingPongPan", "/usr/bin/PingPongPan"},
     {"PulseAudio Equalizer", "pulseaudio-equalizer-gtk", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Qt V4L2 video capture utility", "qvidcap", "/usr/share/icons/hicolor/16x16/apps/qvidcap.png" },
     {"Shotcut", "shotcut ", "/usr/share/icons/hicolor/64x64/apps/org.shotcut.Shotcut.png" },
     {"Shutter Encoder", "shutter-encoder", "///usr/lib/Shutter Encoder/usr/bin/icon.png" },
     {"SimpleScreenRecorder", "simplescreenrecorder --logfile", "/usr/share/icons/hicolor/16x16/apps/simplescreenrecorder.png" },
     {"SoulForce", "/usr/bin/SoulForce"},
     {"Sound Recorder", "gnome-sound-recorder"},
     {"Spotify", "spotify --uri=", "/usr/share/pixmaps/spotify-client.png" },
     {"Stremio", "stremio ", "/usr/share/icons/hicolor/16x16/apps/smartcode-stremio.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"Video4Linux Control Panel", "v4l2ucp", "/usr/share/icons/v4l2ucp.png" },
     {"Volume Icon", "volumeicon", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"Waveform12", "/usr/bin/Waveform12 ", "/usr/share/pixmaps/waveform12.png" },
     {"Xjadeo", "xjadeo", "/usr/share/pixmaps/xjadeo.png" },
     {"glBars", "/usr/bin/glBars"},
     {"guitarix", "guitarix", "/usr/share/pixmaps/gx_head.png" },
     {"guvcview", "guvcview", "/usr/share/icons/hicolor/128x128/apps/guvcview.png" },
     {"mpv Media Player", "mpv --player-operation-mode=pseudo-gui -- ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
     {"ocenaudio", "/usr/bin/ocenaudio ", "/usr/share/icons/hicolor/16x16/apps/ocenaudio.png" },
     {"xine", "xine ", "/usr/share/icons/hicolor/16x16/apps/xine.png" },
     {"zamgrains", "ZamGrains"},
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Android File Transfer (MTP)", "android-file-transfer"},
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Boxes", "gnome-boxes "},
     {"Bulk Rename", "thunar --bulk-rename ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.thunar.png" },
     {"CPU-X", "cpu-x", "/usr/share/icons/hicolor/16x16/apps/cpu-x.png" },
     {"Color Profile Viewer", "gcm-viewer", "/usr/share/icons/hicolor/16x16/apps/gnome-color-manager.png" },
     {"Cool Retro Term", "cool-retro-term", "/usr/share/icons/hicolor/32x32/apps/cool-retro-term.png" },
     {"GParted", "/usr/bin/gparted ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Hardware Locality lstopo", "lstopo"},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KSysGuard", "ksysguard ", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"OpenJDK Java 11 Console", "/usr/lib/jvm/java-11-openjdk/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java11-openjdk.png" },
     {"OpenJDK Java 11 Shell", "xterm -e /usr/lib/jvm/java-11-openjdk/bin/jshell", "/usr/share/icons/hicolor/16x16/apps/java11-openjdk.png" },
     {"OpenJDK Java 17 Console", "/usr/lib/jvm/java-17-openjdk/bin/jconsole"},
     {"OpenJDK Java 17 Shell", "xterm -e /usr/lib/jvm/java-17-openjdk/bin/jshell"},
     {"Oracle Java 18 Console", "/usr/lib/jvm/java-18-jdk/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java-jdk.png" },
     {"Oracle Java 18 Shell", "xterm -e /usr/lib/jvm/java-18-jdk/bin/jshell", "/usr/share/icons/hicolor/16x16/apps/java-jdk.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"QDirStat", "qdirstat "},
     {"QTerminal", "qterminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"QTerminal drop down", "qterminal --drop", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"System Monitor", "gnome-system-monitor"},
     {"System Profiler and Benchmark", "/usr/bin/hardinfo", "/usr/share/icons/hicolor/48x48/apps/hardinfo.png" },
     {"SystemdGenie", "systemdgenie", "/usr/share/icons/gnome/16x16/categories/preferences-desktop.png" },
     {"Thunar File Manager", "thunar ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.thunar.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"dconf Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/ca.desrt.dconf-editor.png" },
     {"fish", "xterm -e fish", "/usr/share/pixmaps/fish.png" },
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
 }

xdgmenu = {
    {"Accessibility", menue0e4fc6213e8b3593495a7260c3a4c2e},
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Archlinux", menu78059f1898ed518c6ccd6a6392fa82c1},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Other", menu6311ae17c1ee52b36e68aaf4ad066387},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Science & Math", menu80d754c83abbbd4ef5d150904efcc86c},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

